# Create a configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: fiap-autenticacao-config
  labels:
    app: fiap-autenticacao
data:
  spring_application_name: 'autenticacao'
  server_servlet_context_path: '/hackathon'
  jwt_expiration: '10'
  server_port: '9091'
  spring_jpa_properties_hibernate_dialect: org.hibernate.dialect.H2Dialect
  spring_datasource_initialization-mode: always
  spring_datasource_initialize: 'true'
  spring_jpa_hibernate_show-sql: 'true'
  spring_jpa_hibernate_ddl-auto: update
  spring_datasource_driver_class_name: org.h2.Driver

#  spring_jpa_properties_hibernate_dialect : org.hibernate.dialect.PostgreSQLDialect
#  jwt_secret : 'fiap@hackathon'
#  spring_datasource_url(spring.datasource.url) : 'jdbc:postgresql://localhost:5432/postgres'
#  spring.datasource.username=postgres
#  spring.datasource.password=postgres


