# Create a service
kind: Service
apiVersion: v1
metadata:
  name: fiap-autenticacao
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::231670762225:role/eks-eks-nodes"
spec:
  selector:
    app: fiap-autenticacao
  ports:
    - name: fiap-autenticacao
      targetPort: 9091
      port: 9091
  type: ClusterIP
